server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://39.106.176.240:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: 123456
    username: root
  redis:
    host: 39.106.176.240 # Redis服务器地址
    database: 0 # 数据库索引(默认为0)
    port: 6379 # 服务器的端口
    password: # Redis服务器连接密码（默认为空）t
    timeout: 3000ms # 连接超时时间（毫秒）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
  elasticsearch:
    rest:
      uris: http://39.106.176.240:9200

# 用admin 123456 这个账号取添加账号mymall 123456
  data:
    mongodb:
      uri: mongodb://mymall:123456@39.106.176.240:27017/mall
#      禁用自动创建索引
      auto-index-creation: false
  rabbitmq:
    host: 39.106.176.240
    port: 5672
    virtual-host: /mall #rabbitmq的虚拟host
    username: mall #rabbitmq的用户名
    password: mall #rabbitmq的密码
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

redis:
  key:
    prefix:
      authCode: "protal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

#自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加密解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)一天
  tokenHead: Bearer #JWT负载中拿到开头

# classpath与classpath*的区别：
# classpath：仅会找本项目的class路径下的配置文件
# classpath*：还会找引入jar中的class配置文件
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com #oss对外服务的访问域名
    accessKeyId: LTAI4GGoqkxcSzPgaPcZs2TD #访问身份验证中用到的用户标识
    accessKeySecret: wsHA14IzUTWRCcBLvWe7v315QFmgxY #用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: zyt-mall #oss的存储空间
    policy:
      expire: 300 #签名有效期（S）
    maxSize: 10 #上传文件大小（M）
    callback: http://localhost:8081/aliyun/oss/callback #文件上传成功的回调地址
    dir:
      prefix: mall/images/ #上传文件夹路径前缀

